### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DhanapalMadheswaran** [AbhishaShah/Registration-and-Login-using-MERN-stack#1]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/home/developer/student/client/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/developer/student/client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/developer/student/client/node_modules/express/lib/router/index.js:317:13)
    at /home/developer/student/client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/developer/student/client/node_modules/express/lib/router/index.js:335:12)
    at next (/home/developer/student/client/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/developer/student/client/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/developer/student/client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/developer/student/client/node_modules/express/lib/router/index.js:317:13)
    at /home/developer/student/client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/developer/student/client/node_modules/express/lib/router/index.js:335:12)
    at next (/home/developer/student/client/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/home/developer/student/client/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/home/developer/student/client/node_modules/express/lib/router/layer.js:95:5)

**Comment by mireshsonkamble** [comment]
any update on this? I am getting same error

**Comment by devlopersabbir** [comment]
@maddysk3 @DhanapalMadheswaran I have fixed that issue in #2 PR
